export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

export const SELECT_PAGE_NUMBER = "SELECT_PAGE_NUMBER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"